[tool.black]
line-length = 88
target-version = ["py311"]

[tool.pytest.ini_options]
pythonpath = ["src"]
addopts = "--maxfail=1 --disable-warnings"

[tool.coverage.run]
source = ["src", "modules", "tools"]
branch = true
